name: main
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
jobs:
  redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install Dependencies
        run: npm install

#  unit:
#    needs: [dependencies]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Setup Node
#        uses: actions/setup-node@v3
#        with:
#          cache: 'npm'
#          node-version: '16'
#      - name: Install Dependencies
#        run: npm ci
#      - name: Run tests
#        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Cache
        run: npm ci
      - name: Build
        run: npm run build
      - name: Save built App
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Get built App
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ github.token }}
          publish_dir: ./dist/pokemon
          force_orphan: true
